export const Headers = [
  { title: 'Yorumlar', isHiddenMobile: true },
  { title: '', isHiddenMobile: true },
  { title: '1', isHiddenMobile: false },
  { title: 'X', isHiddenMobile: false },
  { title: '2', isHiddenMobile: false },
  { title: 'Alt', isHiddenMobile: false },
  { title: 'Üst', isHiddenMobile: false },
  { title: 'H1', isHiddenMobile: true },
  { title: '1', isHiddenMobile: true },
  { title: 'X', isHiddenMobile: true },
  { title: '2', isHiddenMobile: true },
  { title: 'H2', isHiddenMobile: true },
  { title: '1-X', isHiddenMobile: false },
  { title: '1-2', isHiddenMobile: false },
  { title: 'X-2', isHiddenMobile: true },
  { title: 'Var', isHiddenMobile: true },
  { title: 'Yok', isHiddenMobile: true },
  { title: '+99', isHiddenMobile: true },
];
